# MongoDB Connection Secret (included here for clarity; may also be applied separately if needed)
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
stringData:
  connection_string: "mongodb://mongoadmin:WizForTheWorld@10.0.0.6:27017/taskdb?authSource=admin"
---
# ConfigMap for wizexercise.txt
apiVersion: v1
kind: ConfigMap
metadata:
  name: exercise-file
  namespace: default
data:
  wizexercise.txt: |
    This file is part of the Wiz exercise deployment.
    Deployment timestamp: Sun Oct 27 08:26:44 EDT 2024
---
# Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: admin-user
      imagePullSecrets:
        - name: wiztechevalfdc5-auth  # Synced with the pipeline for ACR access
      containers:
      - name: webapp
        image: wiztecheval.azurecr.io/gchen617tasky:latest  # Synced with pipeline image repository
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: connection_string
        volumeMounts:
        - name: exercise-file
          mountPath: /app/wizexercise.txt
          subPath: wizexercise.txt
      volumes:
      - name: exercise-file
        configMap:
          name: exercise-file
---
# Service Account and Role Binding
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: default
