# LoadBalancer Service for External Access
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: webapp
